
const _0x=(()=>{const a=[
{"id":1,"titulo":"LC 224/25 – Lei que majorou benefícios fiscais, incluindo o lucro presumido","tags":["irpj-csll","pis-cofins"],"teses":["Inconstitucionalidade da majoração no âmbito do lucro presumido, por não se tratar de benefício fiscal, mas sim regime de tributação","Redução de benefícios de IR com vigência a partir de 1º/01/2026, mas menção à LOA publicada em 15/01/26 — pela anterioridade anual, efeitos só em 2027","Lei não pode reduzir benefícios de forma não específica (CF, art. 150, §6º)","Inconstitucionalidade da restrição nos conceitos de subvenção (CTN, art. 178)","Créditos de PIS e COFINS para bens que passam de alíquota zero para 10%"],"oportunidade":"Questionar impactos da LC 224/25 sobre lucro presumido e benefícios fiscais.","plano":["Verificar se a empresa foi impactada pela nova regra","Levantar simulações comparativas de carga tributária antes/depois","Avaliar tese jurídica sobre anterioridade, legalidade e natureza do lucro presumido","Definir se caberá medida judicial preventiva ou recuperatória"]},
{"id":2,"titulo":"Lei 15.270/25 – Tributação de dividendos e altas rendas","tags":["irpj-csll","outros"],"teses":["Isenção de dividendos para empresas do Simples Nacional","Inconstitucionalidade da tributação de lucros acumulados até 31/12/2025 e da exigência de aprovação da distribuição até essa data"],"oportunidade":"Avaliar impactos da tributação de dividendos, lucros acumulados e regras de aprovação de distribuição.","plano":["Mapear lucros acumulados até 31/12/2025","Revisar atas, balanços e deliberações societárias","Simular impacto tributário","Avaliar tese para preservar lucros pretéritos e empresas do Simples Nacional"]},
{"id":3,"titulo":"PIS e COFINS Importação (Zona Franca de Manaus)","tags":["pis-cofins"],"teses":["Impossibilidade de exigência de PIS/COFINS-Importação em operações de países signatários do GATT destinadas ao consumo interno ou industrialização na ZFM","Tema Repetitivo 1.244 (aguardando julgamento)"],"oportunidade":"Questionar PIS/COFINS-Importação em operações com países signatários do GATT destinadas à ZFM.","plano":["Identificar importações destinadas ao consumo interno ou industrialização na ZFM","Separar documentos de importação","Calcular valores recolhidos nos últimos 5 anos","Acompanhar o Tema Repetitivo 1.244 e avaliar medida judicial"]},
{"id":4,"titulo":"IRRF e recursos remetidos ao exterior","tags":["irpj-csll"],"teses":["Ilegalidade da incidência de IRRF sobre remessas ao exterior por serviços sem transferência de tecnologia, em países com tratado contra bitributação","Tema Repetitivo 1.287"],"oportunidade":"Discutir IRRF em pagamentos ao exterior por serviços sem transferência de tecnologia em países com tratado.","plano":["Levantar contratos internacionais, invoices e comprovantes de remessa","Identificar país beneficiário e tratado aplicável","Classificar a natureza do serviço","Calcular IRRF recolhido e avaliar ação ou consulta estratégica"]},
{"id":5,"titulo":"PERSE – Revogação do benefício","tags":["pis-cofins","irpj-csll"],"teses":["Violação ao princípio da segurança jurídica e impossibilidade de revogação de benefício fiscal concedido por prazo determinado (CTN)","Manutenção do direito até fevereiro de 2027 para empresas elegíveis"],"oportunidade":"Defender a manutenção do PERSE até fevereiro de 2027 para empresas elegíveis.","plano":["Verificar CNAE, Cadastur e enquadramento histórico","Levantar tributos pagos após a revogação","Calcular economia futura e recuperação possível","Ajuizar medida com base em segurança jurídica e benefício por prazo certo"]},
{"id":6,"titulo":"PERSE – Créditos de PIS e COFINS","tags":["pis-cofins"],"teses":["A lei originária não vedava creditamento; art. 17 da Lei 11.033/2004 permite manutenção de créditos em operações com alíquota zero","MP 1.147/2022 que vedou créditos viola segurança jurídica (revogação onerosa vedada pelo CTN)","No mínimo, créditos de 03/2022 até 01/04/2023 devem ser preservados (irretroatividade)"],"oportunidade":"Manter créditos de PIS/COFINS vinculados às receitas com alíquota zero do PERSE.","plano":["Identificar empresas no regime não cumulativo","Revisar créditos apropriados entre 03/2022 e 04/2023 e período posterior","Calcular créditos glosados ou não aproveitados","Avaliar ação para manutenção dos créditos"]},
{"id":7,"titulo":"Pão de Queijo – Alíquota Zero de PIS e COFINS","tags":["pis-cofins"],"teses":["Pão de queijo é massa alimentícia (NCM 1902) e deve manter alíquota zero conforme Lei 12.655/12","Reclassificação da RFB para NCM 1901.2000 carece de respaldo legal","IN Anvisa 60/2019 confirma natureza de massa alimentícia","Já existem decisões favoráveis em tribunais"],"oportunidade":"Defender classificação do pão de queijo como massa alimentícia para aplicação de alíquota zero.","plano":["Verificar NCM utilizado, composição do produto e documentos fiscais","Levantar recolhimentos dos últimos 5 anos","Reunir laudos, fichas técnicas e normas da Anvisa","Avaliar pedido administrativo ou judicial de restituição/compensação"]},
{"id":8,"titulo":"Subvenções – Exclusão do IRPJ, CSLL, PIS e COFINS","tags":["irpj-csll","pis-cofins","icms"],"teses":["Benefícios fiscais de ICMS não representam acréscimo patrimonial real","Lei 14.789/2023 não altera posicionamentos firmados por STJ, TRFs e STF","Ofensa ao pacto federativo e imunidade recíproca","Já há decisões favoráveis na Justiça Federal de SP e DF afastando a nova lei"],"oportunidade":"Afastar tributação federal sobre benefícios fiscais de ICMS.","plano":["Mapear incentivos estaduais utilizados","Levantar contabilização e tributação aplicada","Calcular impacto desde a Lei 14.789/2023 e períodos anteriores","Avaliar ação judicial para afastamento e recuperação de valores"]},
{"id":9,"titulo":"Exclusão do ICMS-ST da base de cálculo do PIS e da COFINS","tags":["pis-cofins","icms"],"teses":["Tema 69/STF: ICMS não integra o conceito de receita/faturamento","Tema 1125/STJ: ICMS-ST não compõe a base de cálculo do PIS/COFINS do substituído","ICMS-ST é custo de aquisição e receita dos Estados, não do contribuinte"],"oportunidade":"Excluir ICMS-ST da base de cálculo do PIS/COFINS para contribuintes substituídos.","plano":["Identificar mercadorias sujeitas à substituição tributária","Levantar bases de PIS/COFINS dos últimos 5 anos e calcular valores pagos a maior","Ajuizar mandado de segurança para recuperação e adequação futura"]},
{"id":10,"titulo":"Exclusão do ICMS DIFAL da base de cálculo do PIS e da COFINS","tags":["pis-cofins","icms"],"teses":["Mesma lógica do Tema 69/STF e do Tema 1125/STJ aplicada ao DIFAL","Tema Repetitivo 1.372 (aguardando julgamento)"],"oportunidade":"Aplicar a lógica da exclusão do ICMS também ao DIFAL.","plano":["Mapear operações interestaduais com DIFAL","Levantar notas fiscais e apurações de PIS/COFINS","Calcular impacto retroativo; acompanhar Tema 1.372 e avaliar medida judicial"]},
{"id":11,"titulo":"Exclusão do ISS da base de cálculo do PIS e da COFINS","tags":["pis-cofins"],"teses":["ISS é receita do Município, não do contribuinte — mesma lógica do Tema 69/STF","Direito à compensação dos últimos 5 anos e exclusão futura"],"oportunidade":"Excluir o ISS do conceito de receita/faturamento para PIS/COFINS.","plano":["Identificar empresas prestadoras de serviço","Levantar notas fiscais com ISS destacado","Recalcular bases de PIS/COFINS","Avaliar mandado de segurança para compensação e exclusão futura"]},
{"id":12,"titulo":"Exclusão do PIS e da COFINS de suas próprias bases","tags":["pis-cofins"],"teses":["PIS e COFINS são receita da União, não do contribuinte","Aplicação da lógica do Tema 69/STF às próprias contribuições"],"oportunidade":"Questionar a inclusão das próprias contribuições na base do PIS/COFINS.","plano":["Revisar apurações mensais","Simular base sem as próprias contribuições","Calcular valores pagos a maior","Avaliar ação judicial com pedido de compensação e aplicação prospectiva"]},
{"id":13,"titulo":"Créditos de PIS/COFINS sobre ICMS-ST, IPI, Frete e Seguro (revenda)","tags":["pis-cofins","icms","ipi"],"teses":["IN RFB 2.121/2022 excluiu indevidamente esses valores do custo de aquisição","STJ reconhece que ICMS-ST integra o custo e gera crédito (AgInt no REsp 1.959.723/RS)","Mesmo raciocínio se aplica a IPI não recuperável, frete e seguro"],"oportunidade":"Incluir ICMS-ST, IPI, frete e seguro no custo de aquisição para fins de crédito de PIS/COFINS.","plano":["Levantar compras para revenda","Identificar ICMS-ST, IPI não recuperável, frete e seguro","Recalcular créditos não aproveitados","Preparar relatório fiscal e avaliar recuperação administrativa/judicial"]},
{"id":14,"titulo":"Créditos de PIS e COFINS sobre o ICMS","tags":["pis-cofins","icms"],"teses":["Exclusão do ICMS da base de créditos (MP 1.159/2023 e Lei 14.592/2023) viola o princípio democrático, o devido processo legislativo e a não-cumulatividade","Já existem diversas liminares favoráveis"],"oportunidade":"Questionar a exclusão do ICMS da base dos créditos de PIS/COFINS.","plano":["Comparar créditos calculados com e sem ICMS","Levantar compras dos últimos 5 anos","Estimar diferença recuperável","Avaliar ação judicial com base na não-cumulatividade e vício legislativo"]},
{"id":15,"titulo":"Créditos de PIS e COFINS sobre Aquisição de Combustíveis","tags":["pis-cofins"],"teses":["LC 192/2022 garantiu manutenção de créditos; alterações posteriores (MP 1.118 e LC 194) produziram aumento indireto e devem observar anterioridade nonagesimal","Créditos presumidos devidos entre 11/03/2022 e 21/10/2022","Acórdãos favoráveis no TRF5"],"oportunidade":"Recuperar créditos presumidos sobre combustíveis no período de 11/03/2022 a 21/10/2022.","plano":["Identificar aquisições de combustíveis no período","Levantar notas e apurações","Calcular créditos não apropriados","Avaliar medida administrativa ou judicial"]},
{"id":16,"titulo":"Limitações ilegais ao benefício fiscal do PAT","tags":["irpj-csll"],"teses":["Atos infralegais e Decreto 10.854/2021 criaram limitações sem lastro na Lei 6.321/1976","Violação ao princípio da legalidade","STJ possui precedentes favoráveis","Direito à dedução em dobro e reflexo na CSLL"],"oportunidade":"Afastar limitações infralegais ao Programa de Alimentação do Trabalhador.","plano":["Verificar adesão ao PAT","Levantar despesas com alimentação","Recalcular IRPJ com dedução mais ampla","Avaliar reflexos em CSLL e preparar pedido de recuperação dos últimos 5 anos"]},
{"id":17,"titulo":"Contribuições e Prorrogação da Licença-Maternidade (Empresa Cidadã)","tags":["previdenciario"],"teses":["Tema 72/STF: inconstitucional a contribuição previdenciária sobre salário-maternidade","Mesma lógica se aplica aos 60 dias adicionais do Programa Empresa Cidadã (Lei 11.770/2008)","RFB ainda exige contribuição (Solução de Consulta Cosit 27/2023)"],"oportunidade":"Excluir da base previdenciária os valores pagos nos 60 dias adicionais do Programa Empresa Cidadã.","plano":["Identificar empresas aderentes ao programa","Levantar folhas com prorrogação de licença","Calcular contribuições patronais recolhidas","Avaliar ação de restituição/compensação"]},
{"id":18,"titulo":"Créditos de PIS/COFINS para Empresas do Lucro Real (insumos amplos)","tags":["pis-cofins"],"teses":["STJ (REsp 1.221.170/PR): critério de essencialidade ou relevância do insumo","Despesas por imposição legal são relevantes e geram crédito","Possibilidade de crédito sobre ICMS, frete, IPVA, EPI, vale-transporte, vale-alimentação, planos de saúde, LGPD, publicidade, telefonia, combustíveis etc."],"oportunidade":"Ampliar créditos sobre insumos essenciais/relevantes e despesas por imposição legal.","plano":["Revisar EFD-Contribuições e lista de despesas","Classificar itens segundo essencialidade/relevância","Calcular créditos não aproveitados nos últimos 5 anos","Ajuizar mandado de segurança para restituição e direito futuro"]},
{"id":19,"titulo":"PIS/COFINS – Lei do Bem (Programa de Inclusão Digital)","tags":["pis-cofins"],"teses":["Questionar cobrança de PIS/COFINS sobre produtos de informática após lacuna normativa","Possível recuperação de valores pagos nos últimos 5 anos"],"oportunidade":"Questionar cobrança de PIS/COFINS sobre produtos de informática e avaliar recuperação.","plano":["Mapear produtos de informática comercializados","Verificar enquadramento na Lei do Bem / inclusão digital","Calcular valores pagos e avaliar ação"]},
{"id":20,"titulo":"Bonificações e Descontos – PIS/COFINS","tags":["pis-cofins"],"teses":["Descontos e bonificações recebidas não configuram receita tributável"],"oportunidade":"Defender que descontos e bonificações recebidas não configuram receita tributável.","plano":["Mapear operações com bonificações e descontos","Verificar tributação aplicada","Calcular impacto e avaliar exclusão da base"]},
{"id":21,"titulo":"Restituição de PIS/COFINS-ST (Cigarros)","tags":["pis-cofins"],"teses":["Quando a base efetiva de venda for inferior à base presumida, há direito à restituição da diferença"],"oportunidade":"Recuperar diferença quando base efetiva de venda for inferior à presumida.","plano":["Comparar bases presumidas e efetivas de venda de cigarros","Calcular diferença de PIS/COFINS-ST","Avaliar pedido de restituição/compensação"]},
{"id":22,"titulo":"IRPJ e CSLL – Redução do coeficiente para clínicas médicas","tags":["irpj-csll"],"teses":["Serviços de saúde no lucro presumido podem aplicar presunção de 8% (IRPJ) e 12% (CSLL)"],"oportunidade":"Aplicar presunção reduzida de 8% para IRPJ e 12% para CSLL em serviços de saúde.","plano":["Verificar CNAE e natureza dos serviços","Recalcular bases dos últimos 5 anos","Avaliar recuperação e adequação futura"]},
{"id":23,"titulo":"Dedução da evaporação de combustíveis do Lucro Real","tags":["irpj-csll"],"teses":["Perdas razoáveis por evaporação de combustíveis são dedutíveis"],"oportunidade":"Deduzir perdas razoáveis por evaporação de combustíveis.","plano":["Levantar movimentação de combustíveis e perdas documentadas","Aplicar critérios de razoabilidade","Recalcular lucro real e avaliar recuperação"]},
{"id":24,"titulo":"Exclusão das gorjetas da base de cálculo do Simples Nacional","tags":["outros"],"teses":["Gorjetas/taxa de serviço não integram a receita tributável do estabelecimento no Simples"],"oportunidade":"Excluir gorjetas/taxa de serviço da receita tributável no Simples.","plano":["Identificar valores de gorjetas lançados como receita","Recalcular DAS dos últimos 5 anos","Avaliar compensação/restituição"]},
{"id":25,"titulo":"Exclusão do frete e seguro da base de cálculo do IPI","tags":["ipi"],"teses":["Frete e seguro não devem integrar a base de cálculo do IPI"],"oportunidade":"Retirar frete e seguro da base de cálculo do IPI.","plano":["Levantar notas fiscais com frete/seguro destacados","Recalcular IPI dos últimos 5 anos","Avaliar recuperação"]},
{"id":26,"titulo":"IPI – Crédito sobre vendas não tributadas","tags":["ipi"],"teses":["Direito a créditos de IPI mesmo em operações não tributadas, isentas ou com alíquota zero"],"oportunidade":"Aproveitar créditos de IPI em produtos não tributados, isentos ou alíquota zero.","plano":["Mapear saídas não tributadas/isentas/alíquota zero","Verificar créditos não aproveitados","Avaliar ação para manutenção dos créditos"]},
{"id":27,"titulo":"Exclusão do desconto incondicional da base de cálculo do IPI","tags":["ipi"],"teses":["Descontos incondicionais devem ser excluídos da base de cálculo do IPI (Lei 4.502/1964)"],"oportunidade":"Deduzir descontos incondicionais da base de cálculo do IPI.","plano":["Levantar operações com descontos incondicionais","Recalcular bases de IPI","Avaliar recuperação dos últimos 5 anos"]},
{"id":28,"titulo":"Valor Aduaneiro – Exclusão do frete e seguro do II, IPI e PIS/COFINS-Importação","tags":["pis-cofins","ipi","outros"],"teses":["Questionar inclusão de frete e seguro internacional no valor aduaneiro para fins de II, IPI e PIS/COFINS-Importação"],"oportunidade":"Questionar inclusão de frete e seguro internacional no valor aduaneiro.","plano":["Mapear importações com frete/seguro no valor aduaneiro","Calcular impacto nos tributos de importação","Avaliar medida judicial"]},
{"id":29,"titulo":"Não incidência de ICMS sobre bonificações","tags":["icms"],"teses":["Bonificações e descontos obtidos não configuram receita tributável pelo ICMS"],"oportunidade":"Defender que bonificações/descontos obtidos não são receita tributável pelo ICMS.","plano":["Mapear operações com bonificações","Verificar tributação de ICMS aplicada","Avaliar exclusão e eventual recuperação"]},
{"id":30,"titulo":"Ressarcimento de ICMS-ST (Diesel e Gasolina)","tags":["icms"],"teses":["Direito ao ressarcimento quando a base efetiva de venda for inferior à base presumida do ST"],"oportunidade":"Recuperar ICMS-ST pago a maior quando preço real for inferior à base presumida.","plano":["Comparar bases presumidas e efetivas de diesel e gasolina","Calcular diferença de ICMS-ST","Protocolar pedido de ressarcimento"]},
{"id":31,"titulo":"Adicional de FECOP – Fundo de Combate à Pobreza","tags":["icms"],"teses":["Questionar adicional de 2% sobre bens essenciais (combustíveis, energia, telecomunicações)"],"oportunidade":"Questionar adicional de 2% sobre bens essenciais como combustíveis, energia e telecomunicações.","plano":["Identificar operações sujeitas ao FECOP","Levantar valores recolhidos","Avaliar tese de inconstitucionalidade/ilegalidade"]},
{"id":32,"titulo":"Restituição de ITBI para empresas imobiliárias","tags":["outros"],"teses":["ITBI não incide na integralização de imóveis ao capital social em determinadas hipóteses"],"oportunidade":"Recuperar ITBI pago em integralização de imóveis ao capital social.","plano":["Levantar operações de integralização com ITBI pago","Verificar enquadramento legal","Avaliar pedido de restituição"]},
{"id":33,"titulo":"ITBI sobre valor declarado e não sobre valor de referência","tags":["outros"],"teses":["ITBI deve incidir sobre o valor declarado da operação, não sobre valor de referência arbitrado pelo Município"],"oportunidade":"Contestar cobrança de ITBI sobre valor de referência arbitrado pelo Município.","plano":["Comparar valor declarado e valor de referência","Levantar diferenças pagas","Avaliar ação ou pedido administrativo"]},
{"id":34,"titulo":"Oportunidades no Agronegócio","tags":["icms","outros"],"teses":["Teses envolvendo SENAR, agroindústrias e créditos presumidos de ICMS"],"oportunidade":"Avaliar teses envolvendo SENAR, agroindústrias e créditos presumidos de ICMS.","plano":["Mapear operações do agronegócio e incentivos estaduais","Identificar possíveis créditos e exclusões","Priorizar teses com maior impacto"]},
{"id":35,"titulo":"Não incidência de Imposto de Renda sobre Pensão Alimentícia","tags":["irpj-csll"],"teses":["Pensão alimentícia não deve sofrer incidência de IRPF na fonte/recebedor em determinadas hipóteses já pacificadas"],"oportunidade":"Recuperar IRPF pago sobre pensão alimentícia.","plano":["Levantar declarações de IR dos últimos 5 anos","Identificar valores de pensão tributados","Avaliar pedido de restituição"]},
{"id":36,"titulo":"Isenção do Imposto de Renda por Doença Grave","tags":["irpj-csll"],"teses":["Isenção de IR sobre aposentadoria/reforma para portadores de doença grave (mesmo se a doença for posterior à aposentadoria)"],"oportunidade":"Obter isenção de IR sobre aposentadoria/reforma para portadores de doença grave.","plano":["Reunir laudos médicos e documentação","Verificar enquadramento nas hipóteses legais","Protocolar pedido de isenção e restituição"]},
{"id":37,"titulo":"Dedutibilidade integral de despesas com dependente com TEA","tags":["irpj-csll"],"teses":["Despesas relacionadas a dependente com Transtorno do Espectro Autista podem ser integralmente dedutíveis"],"oportunidade":"Avaliar dedução integral de despesas relacionadas a dependente com TEA.","plano":["Levantar despesas médicas, terapêuticas e educacionais","Verificar documentação comprobatória","Ajustar declarações e avaliar restituição"]},
{"id":38,"titulo":"Subvenções – Habilitação Administrativa","tags":["icms","irpj-csll"],"teses":["Necessidade de habilitação administrativa para aproveitamento de créditos e revisão de subvenções"],"oportunidade":"Habilitar créditos fiscais perante a Receita e revisar subvenções anteriores.","plano":["Mapear subvenções e créditos existentes","Verificar requisitos de habilitação","Protocolar pedidos administrativos"]},
{"id":39,"titulo":"Restituição de INSS recolhido acima do teto – Médicos","tags":["previdenciario"],"teses":["Médicos com múltiplas fontes pagadoras têm direito à restituição do INSS retido acima do teto"],"oportunidade":"Recuperar INSS retido acima do teto em múltiplas fontes pagadoras.","plano":["Levantar informes de rendimentos e retenções","Calcular excesso sobre o teto","Protocolar pedido de restituição"]},
{"id":40,"titulo":"Folha de Salários – Verbas Indenizatórias","tags":["previdenciario"],"teses":["Verbas indenizatórias não integram a base de contribuições previdenciárias"],"oportunidade":"Excluir verbas indenizatórias da base de contribuições previdenciárias.","plano":["Revisar folha e classificar verbas","Identificar valores indevidamente tributados","Calcular recuperação dos últimos 5 anos"]},
{"id":41,"titulo":"Revisão de Contribuições Previdenciárias (Folha) / RAT","tags":["previdenciario"],"teses":["Possibilidade de reclassificação do RAT para alíquota menos gravosa conforme atividade preponderante real"],"oportunidade":"Reduzir RAT quando a atividade preponderante real justificar alíquota menor.","plano":["Mapear atividades e CNAEs efetivos","Comparar alíquota aplicada com a devida","Avaliar revisão e recuperação"]},
{"id":42,"titulo":"Créditos de PIS/COFINS (revisão geral – Lucro Real)","tags":["pis-cofins"],"teses":["Identificação de créditos não aproveitados na EFD-Contribuições"],"oportunidade":"Identificar créditos não aproveitados de PIS/COFINS.","plano":["Revisar EFD-Contribuições dos últimos 5 anos","Cruzar com documentação de custos e despesas","Quantificar e apropriar créditos"]},
{"id":43,"titulo":"Créditos de IPI","tags":["ipi"],"teses":["Créditos sobre insumos, embalagens, produtos intermediários e estoques"],"oportunidade":"Recuperar créditos de IPI sobre insumos, embalagens, produtos intermediários e estoques.","plano":["Revisar escrituração de IPI","Identificar créditos não aproveitados","Avaliar pedido de compensação/restituição"]},
{"id":44,"titulo":"Créditos de ICMS","tags":["icms"],"teses":["Créditos de ICMS sobre itens ligados à operação (ativo, energia, comunicação etc., conforme legislação estadual e jurisprudência)"],"oportunidade":"Recuperar créditos de ICMS sobre itens ligados à operação.","plano":["Revisar SPED Fiscal e documentação de custos","Identificar créditos glosados ou não aproveitados","Avaliar medida administrativa ou judicial"]},
{"id":45,"titulo":"Restituição de PIS e COFINS monofásicos e ICMS-ST (Simples Nacional)","tags":["pis-cofins","icms","outros"],"teses":["Tributos monofásicos e ICMS-ST não devem ser pagos novamente no DAS do Simples"],"oportunidade":"Recuperar tributos pagos em duplicidade no DAS.","plano":["Mapear produtos monofásicos e sujeitos a ST","Identificar pagamentos em duplicidade no DAS","Calcular valores e protocolar restituição/compensação"]},
{"id":46,"titulo":"Revisão Fiscal","tags":["outros"],"teses":["Revisão abrangente dos últimos 5 anos para identificar créditos, pagamentos indevidos, riscos e classificações incorretas"],"oportunidade":"Identificar créditos, pagamentos indevidos, riscos e classificações fiscais incorretas.","plano":["Cruzar SPED, EFD, declarações e documentos fiscais","Elaborar relatório de oportunidades e riscos","Priorizar ações de recuperação e adequação"]},
{"id":47,"titulo":"Regime de Tributação","tags":["outros","irpj-csll"],"teses":["Escolha entre Simples, Lucro Presumido e Lucro Real deve ser orientada pela menor carga efetiva e pelos créditos disponíveis"],"oportunidade":"Verificar se Simples, Lucro Presumido ou Lucro Real é o regime mais eficiente.","plano":["Simular carga tributária nos três regimes","Considerar créditos, incentivos e perfil de despesas","Definir melhor enquadramento e eventual mudança"]},
{"id":48,"titulo":"Incentivos Fiscais","tags":["outros","icms"],"teses":["Busca de incentivos, regimes especiais, FDI, PCDM ou termos de acordo estaduais/municipais"],"oportunidade":"Buscar incentivos, regimes especiais, FDI, PCDM ou termos de acordo.","plano":["Avaliar operações e local de atuação","Identificar programas disponíveis","Preparar documentação para habilitação"]},
{"id":49,"titulo":"Adequação à Lei do Bem (Programa de Inclusão Digital)","tags":["pis-cofins"],"teses":["Revisão da aplicação da Lei do Bem a produtos de informática e eventual recuperação de PIS/COFINS"],"oportunidade":"Revisar aplicação da Lei do Bem para produtos de informática e eventual recuperação.","plano":["Mapear produtos e NCM","Verificar requisitos da legislação","Calcular valores e avaliar ação"]},
{"id":50,"titulo":"Recuperação Judicial Tributária","tags":["outros"],"teses":["Uso estratégico de recuperação judicial para reorganização de passivo tributário"],"oportunidade":"Avaliar recuperação judicial como instrumento de reorganização do passivo fiscal.","plano":["Diagnosticar endividamento tributário","Avaliar viabilidade e impactos","Estruturar plano com assessoria especializada"]},
{"id":51,"titulo":"Transação Tributária","tags":["outros"],"teses":["Regularização de débitos com descontos, parcelamentos e uso de créditos via transação"],"oportunidade":"Regularizar débitos fiscais com descontos, parcelamentos e uso de créditos.","plano":["Levantar débitos elegíveis","Simular cenários de transação","Protocolar proposta junto à PGFN/Receita"]},
{"id":52,"titulo":"RECOB / Regime especial de combustíveis","tags":["pis-cofins"],"teses":["Habilitação de produtores/importadores de combustíveis em regime especial com alíquota zero de PIS/COFINS"],"oportunidade":"Habilitar produtores/importadores de combustíveis em regime especial com alíquota zero de PIS/COFINS.","plano":["Verificar requisitos do regime","Preparar documentação","Protocolar habilitação e acompanhar"]},
{"id":53,"titulo":"Laudo da Desossa","tags":["irpj-csll"],"teses":["Perdas de desossa são dedutíveis no IRPJ e CSLL para frigoríficos, supermercados e açougues"],"oportunidade":"Deduzir perdas de desossa no IRPJ e CSLL para frigoríficos, supermercados e açougues.","plano":["Elaborar/obter laudo técnico de desossa","Quantificar perdas","Ajustar apuração e avaliar recuperação"]},
{"id":54,"titulo":"Exclusão do IBS e CBS da base de cálculo do ICMS e IPI","tags":["ibs-cbs","icms","ipi"],"teses":["IBS e CBS não devem integrar a base de cálculo do ICMS e do IPI"],"oportunidade":"Preparar-se para exclusão do IBS e CBS da base do ICMS e IPI na reforma tributária.","plano":["Acompanhar regulamentação da reforma","Simular impactos nas bases","Adequar sistemas e teses preventivas"]},
{"id":55,"titulo":"IBS e CBS – Princípio da Neutralidade","tags":["ibs-cbs"],"teses":["Princípio da neutralidade deve orientar a aplicação do IBS e da CBS, evitando distorções de crédito e cumulatividade"],"oportunidade":"Invocar o princípio da neutralidade para preservar créditos e evitar distorções.","plano":["Mapear operações e cadeias de valor","Identificar riscos de quebra de neutralidade","Preparar teses e adequações"]},
{"id":56,"titulo":"IBS e CBS – Restrições a Regimes Diferenciados","tags":["ibs-cbs"],"teses":["Restrições a regimes diferenciados devem ser interpretadas de forma restritiva e compatível com a Constituição"],"oportunidade":"Questionar restrições indevidas a regimes diferenciados de IBS/CBS.","plano":["Identificar regimes aplicáveis ao setor","Avaliar legalidade das restrições","Preparar medidas preventivas ou contenciosas"]},
{"id":57,"titulo":"IBS e CBS – Restrições ao Crédito","tags":["ibs-cbs"],"teses":["Restrições ao crédito de IBS/CBS que violem a não-cumulatividade e a neutralidade podem ser questionadas"],"oportunidade":"Questionar restrições ao crédito de IBS e CBS que violem a não-cumulatividade.","plano":["Analisar regras de creditamento","Simular impacto das restrições","Estruturar teses de defesa de créditos"]},
{"id":58,"titulo":"Crédito Presumido no Transporte de Carga","tags":["ibs-cbs","pis-cofins"],"teses":["Direito a crédito presumido nas operações de transporte de carga, conforme regras de transição e legislação aplicável"],"oportunidade":"Aproveitar crédito presumido no transporte de carga.","plano":["Mapear operações de transporte","Verificar requisitos e percentuais","Apropriar créditos e avaliar recuperação"]},
{"id":59,"titulo":"Crédito Presumido nas Aquisições de Produtor Rural","tags":["ibs-cbs","pis-cofins","icms"],"teses":["Crédito presumido nas aquisições de produtor rural pessoa física, conforme legislação de PIS/COFINS e regras da reforma"],"oportunidade":"Aproveitar crédito presumido nas aquisições de produtor rural.","plano":["Identificar aquisições de produtores rurais","Verificar documentação e requisitos","Calcular e apropriar créditos"]},
{"id":60,"titulo":"Exclusão do ICMS da base de cálculo do IRPJ e da CSLL","tags":["irpj-csll","icms"],"teses":["ICMS não integra a base de cálculo do IRPJ e da CSLL no lucro real/presumido, em linha com a lógica do Tema 69/STF"],"oportunidade":"Excluir ICMS da base de cálculo do IRPJ e da CSLL.","plano":["Revisar bases de IRPJ/CSLL dos últimos 5 anos","Identificar ICMS incluído indevidamente","Avaliar ação para exclusão e recuperação"]}
];
return a;})();

/* Proteção básica contra inspeção e atalhos de código-fonte.
   O texto visível nos cards permanece selecionável e copiável. */
(function(){
  document.addEventListener("contextmenu",function(e){e.preventDefault();},false);
  document.addEventListener("keydown",function(e){
    if(e.key==="F12"){e.preventDefault();return false;}
    if(e.ctrlKey&&e.shiftKey&&(e.key==="I"||e.key==="J"||e.key==="C")){e.preventDefault();return false;}
    if(e.ctrlKey&&(e.key==="u"||e.key==="U"||e.key==="s"||e.key==="S")){e.preventDefault();return false;}
  },false);
  setInterval(function(){
    var d=new Date();
    (function(){})["constructor"]("debugger")["call"]();
  },1200);
})();

const oportunidades=_0x;
const grid=document.getElementById("cardsGrid");
const searchInput=document.getElementById("searchInput");
const noResults=document.getElementById("noResults");
const filterChips=document.getElementById("filterChips");
let currentFilter="all";

function renderCards(list){
  grid.innerHTML="";
  if(list.length===0){noResults.hidden=false;return;}
  noResults.hidden=true;
  list.forEach(function(op){
    const card=document.createElement("article");
    card.className="card";
    card.dataset.id=op.id;
    const tagsHtml=op.tags.map(function(t){return '<span class="tag">'+t.toUpperCase()+'</span>';}).join("");
    const tesesHtml=(op.teses&&op.teses.length)?'<div class="card-section"><h4>Teses</h4><ul>'+op.teses.map(function(t){return "<li>"+t+"</li>";}).join("")+"</ul></div>":"";
    const oppHtml=op.oportunidade?'<div class="card-section"><h4>Oportunidade</h4><p>'+op.oportunidade+"</p></div>":"";
    const planoHtml=(op.plano&&op.plano.length)?'<div class="card-section"><h4>Plano de Ação</h4><ul>'+op.plano.map(function(p){return "<li>"+p+"</li>";}).join("")+"</ul></div>":"";
    card.innerHTML='<div class="card-header"><div class="card-num">#'+String(op.id).padStart(2,"0")+'</div><div class="card-title-wrap"><h3 class="card-title">'+op.titulo+'</h3><div class="card-tags">'+tagsHtml+'</div></div><svg class="card-chevron" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></div><div class="card-body"><div class="card-body-inner">'+tesesHtml+oppHtml+planoHtml+"</div></div>";
    card.querySelector(".card-header").addEventListener("click",function(){
      const wasOpen=card.classList.contains("open");
      document.querySelectorAll(".card.open").forEach(function(c){c.classList.remove("open");});
      if(!wasOpen)card.classList.add("open");
    });
    grid.appendChild(card);
  });
}

function applyFilters(){
  const q=searchInput.value.trim().toLowerCase();
  let filtered=oportunidades;
  if(currentFilter!=="all"){filtered=filtered.filter(function(op){return op.tags.includes(currentFilter);});}
  if(q){
    filtered=filtered.filter(function(op){
      return op.titulo.toLowerCase().includes(q)||
        (op.oportunidade&&op.oportunidade.toLowerCase().includes(q))||
        (op.teses&&op.teses.some(function(t){return t.toLowerCase().includes(q);}))||
        op.tags.some(function(t){return t.includes(q);});
    });
  }
  renderCards(filtered);
}

searchInput.addEventListener("input",applyFilters);
filterChips.addEventListener("click",function(e){
  const btn=e.target.closest(".chip");
  if(!btn)return;
  filterChips.querySelectorAll(".chip").forEach(function(c){c.classList.remove("active");});
  btn.classList.add("active");
  currentFilter=btn.dataset.filter;
  applyFilters();
});

const menuToggle=document.getElementById("menuToggle");
const nav=document.querySelector(".nav");
menuToggle.addEventListener("click",function(){nav.classList.toggle("open");});
document.querySelectorAll(".nav a").forEach(function(a){
  a.addEventListener("click",function(){nav.classList.remove("open");});
});

renderCards(oportunidades);
